// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fiptzxpwqntrxcobotpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpcHR6eHB3cW50cnhjb2JvdHBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMjYwNzEsImV4cCI6MjA1OTcwMjA3MX0.oyRKDywjKHpmHx0iWZRAMRtDMG1T-2Chb3bTYwUijK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);